<RootWidget>:
    Button:
        # Não queremos definir o size de forma percentual
        size_hint: None, None
        # L x H
        size: 350, 50
        x: 100
        y: 350
        text: "px"

    Button:
        size_hint: None, None
        size: dp(350), dp(50)
        pos: dp(80), dp(200)
        text: "dp"

    Button:
        size_hint: .5, .09
        pos_hint: {"x": .1, "y": .1}
        text: "%"
